### ISSUE TITLE
How to handle any random (custom) hotkey or keyboard shortcut?

### ISSUE THREAD

**Issue by mo-han** [fding/pyedifice#19]
Say, what if I'd like the app to quit when `Esc` is tapped? Or when a specific text input area is focused, pressing `Enter` has the same effect as clicking a specific button? I believe this is doable via Qt, thus doable via pyedifice as well. But I'm not skillful enough to implement this, any suggestions?

**Comment by fding** [comment]
I added the key_down and key_up events, hopefully these events will allow you to do what you want!
