### ISSUE TITLE
Difficulties in dynamic reloading a script

### ISSUE THREAD

**Issue by AnselmJeong** [fding/pyedifice#5]
I've been trying to replicate the tutorial example on my computer. 
Let's say my script is named `temp.py`

This python script went well with the command `python temp.py`.

However, when I issued the command `python -m edifice temp.py MyApp`, it crashed with the error message
 `TypeError: the 'package' argument is required to perform a relative import for '.temp'`

If I changed the filename with the absolute path like 
`python -m edifice E:/temp.py MyApp`, this time the error message was 
`ModuleNotFoundError: No module named '/E:'`.

I'm in windows machine, therefore it might be the problem with absolute path expression. Is there any walkaround?

Thanks in advance.....

**Comment by fding** [comment]
Yes, there is currently a bug, and the pull request to fix it: https://github.com/fding/pyedifice/pull/4. I'll let you know when this is fixed!

**Comment by fding** [comment]
This issue should now be fixed. You can get the fix by either pulling from this repo (master branch) or by updating via pip:
`pip install pyedifice==0.0.8`. You should be able to run with the relative path. Let me know if this works.

**Comment by AnselmJeong** [comment]
It works without a glitch...... Thanks....
